FROM node:23-slim AS build

WORKDIR /app

COPY frontend/ .
RUN npm install
RUN npm run build -- --output-path=dist/frontend

FROM nginx:alpine

COPY --from=build /app/dist/frontend/browser /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf
